version: '3.8'

services:
  app:
    build:
      context: .
      target: prod
    image: "streamlit-template-prod"
    volumes:
      - ./src:/work/src
    ports:
      - "8501:8501"
    restart: always
    command: ["streamlit", "run", "main.py"]
